# Install pre-commit hooks via
# pre-commit install

# We exclude text notebooks as we want to commit the plain Jupytext representation
exclude: >
    (?x)^(
      demo/.*|
      tests/notebooks/.*|
    )$
repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    - id: check-json
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace

  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
    - id: autoflake
      args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variable']

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
    - id: flake8

  - repo: https://github.com/PyCQA/isort
    rev: 5.7.0
    hooks:
      # isort needs the 'black' profile when used in combination with black
      # See https://github.com/PyCQA/isort/issues/1518
    - id: isort
      args: ["--profile", "black"]

  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    - id: black
